# CONFIGURAÇÕES GERAIS DO QUARKUS
quarkus.application.name=HCPlus10
quarkus.http.port=8080
quarkus.log.console.color=true

# CONFIGURAÇÃO DE CONEXÃO COM O BANCO DE DADOS ORACLE
quarkus.datasource.db-kind=oracle
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
quarkus.datasource.username=Rm564662
quarkus.datasource.password=020207
quarkus.datasource.jdbc.driver=oracle.jdbc.driver.OracleDriver

# POOL DE CONEXÕES
quarkus.datasource.jdbc.min-size=1
quarkus.datasource.jdbc.max-size=10

# LOGS
quarkus.log.level=INFO
quarkus.log.category."io.quarkus".level=DEBUG

# ? LIBERAÇÃO DE CORS PARA FRONT-END (OBRIGATÓRIO)
quarkus.http.cors=true
quarkus.http.cors.origins=*
