# CONFIGURAÇÕES GERAIS DO QUARKUS
quarkus.application.name=HCPlus10
quarkus.http.port=8080
quarkus.log.console.color=true


# CONEXÃO COM BANCO DE DADOS ORACLE (FIAP)
quarkus.datasource.db-kind=oracle
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
quarkus.datasource.username=Rm564662
quarkus.datasource.password=020207
quarkus.datasource.jdbc.driver=oracle.jdbc.driver.OracleDriver

# Pool de conexões
quarkus.datasource.jdbc.min-size=1
quarkus.datasource.jdbc.max-size=10


# LOGS
quarkus.log.level=INFO
quarkus.log.category."io.quarkus".level=DEBUG


# CORS (OBRIGATÓRIO PARA FUNCIONAR COM VERCEL)
# Ativa CORS
quarkus.http.cors=true

# Libera origens permitidas (local + vercel)
quarkus.http.cors.origins=http://localhost:5173,https://eloithealth.vercel.app

# Libera métodos HTTP usados pelo front-end
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

# Libera headers necessários para envio de JSON
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

# Permite envio de cookies/credenciais (caso use login futuramente)
quarkus.http.cors.access-control-allow-credentials=true
