# CONFIGURAÇÕES GERAIS DO QUARKUS
quarkus.application.name=HCPlus10
quarkus.http.port=8080
quarkus.log.console.color=true


#CONFIGURAÇÃO DE CONEXÃO COM O BANCO DE DADOS ORACLE
quarkus.datasource.db-kind=oracle
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
quarkus.datasource.username=Rm564662
quarkus.datasource.password=020207
quarkus.datasource.jdbc.driver=oracle.jdbc.driver.OracleDriver

# Controla o pool de conexões
quarkus.datasource.jdbc.min-size=1
quarkus.datasource.jdbc.max-size=10

# ?? HIBERNATE / JPA (caso queira ativar depois)
# Se futuramente for usar JPA / ORM, habilite estas linhas:
# quarkus.hibernate-orm.database.generation=update
# quarkus.hibernate-orm.log.sql=true
# quarkus.hibernate-orm.sql-load-script=no-file

# ? CONFIGURAÇÃO DE AMBIENTE DEV

# Mostra logs detalhados no modo dev
quarkus.log.level=INFO
quarkus.log.category."io.quarkus".level=DEBUG